/**
 * La SEULE liste des chemins Firestore (ARCHITECTURE §6). Le lint interdit de nommer une
 * collection ailleurs que dans ce paquet.
 */
export const collections = {
  users: 'users',
  admins: 'admins',
  rolesAdmin: 'rolesAdmin',
  invitations: 'invitations',
  revendications: 'revendications',
  demandesAcces: 'demandesAcces',
  sirenIndex: 'sirenIndex',
  artisans: 'artisans',
  artisansPublic: 'artisansPublic',
  artisanScores: 'artisanScores',
  sanctions: 'sanctions',
  notesInternes: 'notesInternes',
  demandes: 'demandes',
  dossiersDiag: 'dossiersDiag',
  matching: 'matching',
  sourcesDemandes: 'sourcesDemandes',
  importsDemandes: 'importsDemandes',
  preuvesConsentement: 'preuvesConsentement',
  appelsOffres: 'appelsOffres',
  grillesTarifaires: 'grillesTarifaires',
  achatsLeads: 'achatsLeads',
  portefeuilles: 'portefeuilles',
  packsCredits: 'packsCredits',
  remboursementsLeads: 'remboursementsLeads',
  avis: 'avis',
  abonnements: 'abonnements',
  factures: 'factures',
  paiements: 'paiements',
  codesPromo: 'codesPromo',
  stripeEvents: 'stripeEvents',
  communes: 'communes',
  annonces: 'annonces',
  contacts: 'contacts',
  litiges: 'litiges',
  emails: 'emails',
  suppressions: 'suppressions',
  evenements: 'evenements',
  auditLog: 'auditLog',
  rateLimits: 'rateLimits',
  idempotence: 'idempotence',
  rgpdDemandes: 'rgpdDemandes',
  filesModeration: 'filesModeration',
  migrations: 'migrations',
  prospects: 'prospects',
  cycleEtat: 'cycleEtat',
  cycleTraces: 'cycleTraces',
  cycleStats: 'cycleStats',
  sequences: 'sequences',
  pagesSuivies: 'pagesSuivies',
  comportementSessions: 'comportementSessions',
  comportementAgregats: 'comportementAgregats',
  comportementAlertes: 'comportementAlertes',
  abTests: 'abTests',
  iaContexte: 'iaContexte',
  iaAnalyses: 'iaAnalyses',
  iaRecommandations: 'iaRecommandations',
  iaQuotas: 'iaQuotas',
  iaRedactions: 'iaRedactions',
  brouillons: 'brouillons',
  brouillonsOnboarding: 'brouillonsOnboarding',
  simulations: 'simulations',
  cacheSirene: 'cacheSirene',
  /** Émulateur uniquement : envois capturés pour les tests de bout en bout (secrets compris). */
  capturesEmulateur: 'capturesEmulateur',
} as const;

export type NomCollection = keyof typeof collections;

/** Chemins complets des documents et sous-collections. */
export const chemins = {
  user: (uid: string) => `users/${uid}`,
  brouillonOnboarding: (id: string) => `brouillonsOnboarding/${id}`,
  consentements: (uid: string) => `users/${uid}/consentements`,
  notifications: (uid: string) => `users/${uid}/notifications`,
  admin: (uid: string) => `admins/${uid}`,
  artisan: (id: string) => `artisans/${id}`,
  artisanPublic: (id: string) => `artisansPublic/${id}`,
  facturationPrivee: (id: string) => `artisans/${id}/prive/facturation`,
  membres: (aid: string) => `artisans/${aid}/membres`,
  membre: (aid: string, uid: string) => `artisans/${aid}/membres/${uid}`,
  etablissements: (aid: string) => `artisans/${aid}/etablissements`,
  documents: (aid: string) => `artisans/${aid}/documents`,
  realisations: (aid: string) => `artisans/${aid}/realisations`,
  disponibilites: (aid: string) => `artisans/${aid}/disponibilites`,
  statsJour: (aid: string, jour: string) => `artisans/${aid}/statsJour/${jour}`,
  demande: (id: string) => `demandes/${id}`,
  attributions: (demandeId: string) => `demandes/${demandeId}/attributions`,
  attribution: (demandeId: string, artisanId: string) =>
    `demandes/${demandeId}/attributions/${artisanId}`,
  messages: (demandeId: string) => `demandes/${demandeId}/messages`,
  dossierDiag: (id: string) => `dossiersDiag/${id}`,
  attributionsDiag: (dossierId: string) => `dossiersDiag/${dossierId}/attributions`,
  configMatching: () => 'matchingConfig/actif',
  versionsMatching: () => 'matchingConfig/actif/versions',
  appelOffres: (id: string) => `appelsOffres/${id}`,
  deblocage: (aoId: string, artisanId: string) => `appelsOffres/${aoId}/deblocages/${artisanId}`,
  reponse: (aoId: string, artisanId: string) => `appelsOffres/${aoId}/reponses/${artisanId}`,
  historiquePrix: (aoId: string) => `appelsOffres/${aoId}/historiquePrix`,
  portefeuille: (aid: string) => `portefeuilles/${aid}`,
  mouvements: (aid: string) => `portefeuilles/${aid}/mouvements`,
  avis: (id: string) => `avis/${id}`,
  auteurAvis: (id: string) => `avis/${id}/prive/auteur`,
  signalements: (id: string) => `avis/${id}/signalements`,
  prestationItem: (id: string) => `referentiel/prestations/items/${id}`,
  prestationPrix: (id: string) => `referentiel/prestations/prix/${id}`,
  diagnosticItem: (id: string) => `referentiel/diagnostics/items/${id}`,
  diagnosticPrix: (id: string) => `referentiel/diagnostics/prix/${id}`,
  metiers: () => 'referentiel/metiers/items',
  labels: () => 'referentiel/labels/items',
  intentions: () => 'referentiel/recherche/intentions',
  metiersRecherche: () => 'referentiel/recherche/metiers',
  synonymes: () => 'referentiel/recherche/synonymes/global',
  statsPublic: () => 'stats/public',
  configApp: () => 'config/app',
  configFlags: () => 'config/flags',
  flagsArtisan: (aid: string) => `config/flags/artisans/${aid}`,
  configCycle: () => 'config/cycle',
  configComportement: () => 'config/comportement',
  configIa: () => 'config/ia',
  versionsSequence: (id: string) => `sequences/${id}/versions`,
} as const;

/** Collection group des attributions (demandes et diagnostics) : filtrer par `artisanId`. */
export const GROUPE_ATTRIBUTIONS = 'attributions';

/** Chemins Storage (storage.rules) : fichiers de l'entreprise. */
export const fichiers = {
  document: (aid: string, docId: string, nom: string) =>
    `artisans/${aid}/documents/${docId}/${nom}`,
  logo: (aid: string, nom: string) => `artisans/${aid}/logo/${nom}`,
  realisation: (aid: string, rid: string, nom: string) =>
    `artisans/${aid}/realisations/${rid}/${nom}`,
} as const;
